-- Database for logging
create database if NOT exists yprov
  character set utf8mb4
  collate utf8mb4_unicode_ci;

use yprov;

create table if not exists visit_logs (
	id int auto_increment not null,
	uuid varchar(255) not null,
	unique_visitor_hash varchar(255) not null,
	country varchar(2),
	region varchar(255),
	city varchar(255),
	browser varchar(255),
	os varchar(255),
	device varchar(255),
	created_at datetime not null default CURRENT_TIMESTAMP,
	primary key(id)
) Engine=InnoDB default charset=utf8mb4 collate=utf8mb4_unicode_ci;

create table if not exists upload_logs (
	id int auto_increment not null,
	visit_log int not null,
	foreign key(visit_log) references visit_logs(id)
		on delete cascade
		on update cascade,
	name varchar(255) not null,
	size double not null,
	created_at datetime not null default CURRENT_TIMESTAMP,
	primary key(id)
) Engine=InnoDB default charset=utf8mb4 collate=utf8mb4_unicode_ci;

create table if not exists country_names (
	code varchar(2) not null,
	name varchar(255) not null,
	primary key(code)
) Engine=InnoDB default charset=utf8mb4 collate=utf8mb4_unicode_ci;

insert into country_names (code, name) values
	("AD", "Andorra"),
	("AE", "United Arab Emirates"),
	("AF", "Afghanistan"),
	("AG", "Antigua and Barbuda"),
	("AI", "Anguilla"),
	("AL", "Albania"),
	("AM", "Armenia"),
	("AO", "Angola"),
	("AQ", "Antarctica"),
	("AR", "Argentina"),
	("AS", "American Samoa"),
	("AT", "Austria"),
	("AU", "Australia"),
	("AW", "Aruba"),
	("AX", "Åland Islands"),
	("AZ", "Azerbaijan"),
	("BA", "Bosnia and Herzegovina"),
	("BB", "Barbados"),
	("BD", "Bangladesh"),
	("BE", "Belgium"),
	("BF", "Burkina"),
	("BG", "Bulgaria"),
	("BH", "Bahrain"),
	("BI", "Burundi"),
	("BJ", "Benin"),
	("BL", "Saint Barthélemy"),
	("BM", "Bermuda"),
	("BN", "Brunei"),
	("BO", "Bolivia"),
	("BQ", "Bonaire"),
	("BR", "Brazil"),
	("BS", "Bahamas"),
	("BT", "Bhutan"),
	("BV", "Bouvet Island"),
	("BW", "Botswana"),
	("BY", "Belarus"),
	("BZ", "Belize"),
	("CA", "Canada"),
	("CC", "Cocos (Keeling) Islands"),
	("CD", "Democratic Republic of the Congo"),
	("CF", "Central African Republic"),
	("CG", "Congo"),
	("CH", "Switzerland"),
	("CI", "Ivory Coast"),
	("CK", "Cook Islands"),
	("CL", "Chile"),
	("CM", "Cameroon"),
	("CN", "China"),
	("CO", "Colombia"),
	("CR", "Costa"),
	("CU", "Cuba"),
	("CV", "Cabo Verde"),
	("CW", "Curaçao"),
	("CX", "Christmas Island"),
	("CY", "Cyprus"),
	("CZ", "Czech Republic"),
	("DE", "Germany"),
	("DJ", "Djibouti"),
	("DK", "Denmark"),
	("DM", "Dominica"),
	("DO", "Dominican Republic"),
	("DZ", "Algeria"),
	("EC", "Ecuador"),
	("EE", "Estonia"),
	("EG", "Egypt"),
	("EH", "Western Sahara"),
	("ER", "Eritrea"),
	("ES", "Spain"),
	("ET", "Ethiopia"),
	("FI", "Finland"),
	("FJ", "Fiji"),
	("FK", "Falkland Islands"),
	("FM", "Micronesia (Federated States of)"),
	("FO", "Faroe"),
	("FR", "France"),
	("GA", "Gabon"),
	("GB", "United Kingdom of Great Britain and Northern Ireland"),
	("GD", "Grenada"),
	("GE", "Georgia"),
	("GF", "French Guiana"),
	("GG", "Guernsey"),
	("GH", "Ghana"),
	("GI", "Gibraltar"),
	("GL", "Greenland"),
	("GM", "Gambia"),
	("GN", "Guinea"),
	("GP", "Guadeloupe"),
	("GQ", "Equatorial Guinea"),
	("GR", "Greece"),
	("GS", "South Georgia and the South Sandwich Islands"),
	("GT", "Guatemala"),
	("GU", "Guam"),
	("GW", "Guinea-Bissau"),
	("GY", "Guyana"),
	("HK", "Hong"),
	("HM", "Heard Island and McDonald Islands"),
	("HN", "Honduras"),
	("HR", "Croatia"),
	("HT", "Haiti"),
	("HU", "Hungary"),
	("ID", "Indonesia"),
	("IE", "Ireland"),
	("IL", "Israel"),
	("IM", "Isle of Man"),
	("IN", "India"),
	("IO", "British Indian Ocean Territory"),
	("IQ", "Iraq"),
	("IR", "Iran"),
	("IS", "Iceland"),
	("IT", "Italy"),
	("JE", "Jersey"),
	("JM", "Jamaica"),
	("JO", "Jordan"),
	("JP", "Japan"),
	("KE", "Kenya"),
	("KG", "Kyrgyzstan"),
	("KH", "Cambodia"),
	("KI", "Kiribati"),
	("KM", "Comoros Kitts and Nevis"),
	("KN", "Saint"),
	("KP", "North Korea"),
	("KR", "South Korea"),
	("KW", "Kuwait"),
	("KY", "Cayman Islands"),
	("KZ", "Kazakhstan"),
	("LA", "Laos"),
	("LB", "Lebanon"),
	("LC", "Saint Lucia"),
	("LI", "Liechtenstein"),
	("LK", "Sri Lanka"),
	("LR", "Liberia"),
	("LS", "Lesotho"),
	("LT", "Lithuania"),
	("LU", "Luxembourg"),
	("LV", "Latvia"),
	("LY", "Libya"),
	("MA", "Morocco"),
	("MC", "Monaco"),
	("MD", "Moldova"),
	("ME", "Montenegro"),
	("MF", "Saint Martin"),
	("MG", "Madagascar"),
	("MH", "Marshall Islands"),
	("MK", "North Macedonia"),
	("ML", "Mali"),
	("MM", "Myanmar"),
	("MN", "Mongolia"),
	("MO", "Macao"),
	("MP", "Northern Mariana Islands"),
	("MQ", "Martinique"),
	("MR", "Mauritania"),
	("MS", "Montserrat"),
	("MT", "Malta"),
	("MU", "Mauritius"),
	("MV", "Maldives"),
	("MW", "Malawi"),
	("MX", "Mexico"),
	("MY", "Malaysia"),
	("MZ", "Mozambique"),
	("NA", "Namibia"),
	("NC", "New Caledonia"),
	("NE", "Niger"),
	("NF", "Norfolk Island"),
	("NG", "Nigeria"),
	("NI", "Nicaragua"),
	("NL", "Netherlands"),
	("NO", "Norway"),
	("NP", "Nepal"),
	("NR", "Nauru"),
	("NU", "Niue"),
	("NZ", "New Zealand"),
	("OM", "Oman"),
	("PA", "Panama"),
	("PE", "Peru"),
	("PF", "French Polynesia"),
	("PG", "Papua New Guinea"),
	("PH", "Philippines"),
	("PK", "Pakistan"),
	("PL", "Poland"),
	("PM", "Saint Pierre and Miquelon"),
	("PN", "Pitcairn"),
	("PR", "Puerto Rico"),
	("PS", "Palestine"),
	("PT", "Portugal"),
	("PW", "Palau"),
	("PY", "Paraguay"),
	("QA", "Qatar"),
	("RE", "Réunion"),
	("RO", "Romania"),
	("RS", "Serbia"),
	("RU", "Russia"),
	("RW", "Rwanda"),
	("SA", "Saudi Arabia"),
	("SB", "Solomon Islands"),
	("SC", "Seychelles"),
	("SD", "Sudan"),
	("SE", "Sweden"),
	("SG", "Singapore"),
	("SH", "Saint Helen"),
	("SI", "Slovenia"),
	("SJ", "Svalbard and Jan Mayen"),
	("SK", "Slovakia"),
	("SL", "Sierra Leone"),
	("SM", "San Marino"),
	("SN", "Senegal"),
	("SO", "Somalia"),
	("SR", "Suriname"),
	("SS", "South"),
	("ST", "Sao Tome and Principe"),
	("SV", "El"),
	("SX", "Sint Maarten"),
	("SY", "Syria"),
	("SZ", "Eswatini"),
	("TC", "Turks and Caicos Islands"),
	("TD", "Chad"),
	("TF", "French Southern Territories"),
	("TG", "Togo"),
	("TH", "Thailand"),
	("TJ", "Tajikistan"),
	("TK", "Tokelau"),
	("TL", "Timor-Leste"),
	("TM", "Turkmenistan"),
	("TN", "Tunisia"),
	("TO", "Tonga"),
	("TR", "Turkey"),
	("TT", "Trinidad and Tobago"),
	("TV", "Tuvalu"),
	("TW", "Taiwan"),
	("TZ", "Tanzania"),
	("UA", "Ukraine"),
	("UG", "Uganda"),
	("UM", "United States Minor Outlying Islands"),
	("US", "United States of America"),
	("UY", "Uruguay"),
	("UZ", "Uzbekistan"),
	("VA", "Holy See"),
	("VC", "Saint Vincent and the Grenadines"),
	("VE", "Venezuela"),
	("VG", "Virgin Islands (British)"),
	("VI", "Virgin Islands (U.S.)"),
	("VN", "Vietnam"),
	("VU", "Vanuatu"),
	("WF", "Wallis and Futuna"),
	("WS", "Samoa"),
	("YE", "Yemen"),
	("YT", "Mayotte"),
	("ZA", "South Africa"),
	("ZM", "Zambia"),
	("ZW", "Zimbabwe");
