import graph_tool.all as gt
import utils as ut
import pattern_reducers as red

type LineComp = tuple[str, str, str, str]

def merge_by_line(
  g: gt.Graph, entity_based: bool, reduce_io: bool, file_name: str,
  props: ut.CustomPropertiesList
) -> gt.GraphView:
  """Uses jupyter info to merge together nodes generated by the same call.
  The graph reduced according to this strategy is returned."""

  subgraph: gt.GraphView
  if entity_based:
    subgraph = red.get_entity_subgraph(g)
  else:
    subgraph = red.get_activity_subgraph(g)

  line_comps: dict[LineComp, set[int]] = {}
  vertex_to_line_comp: dict[int, LineComp] = {}
  for v in subgraph.vertices():
    index = g.vertex_properties[ut.Props.CELL_INDEX.value][v]
    line = g.vertex_properties[ut.Props.CELL_LINE.value][v]
    start = g.vertex_properties[ut.Props.CELL_LINE_START.value][v]
    end = g.vertex_properties[ut.Props.CELL_LINE_END.value][v]
    key = (index, start, end, line)
    others: set[int] = line_comps.get(key, set())
    others.add(v)
    line_comps[key] = others
    vertex_to_line_comp[v] = key

  def key_fn(key: LineComp, level: int) -> str:
    return f'{key[0]}_{key[1]}_{key[2]}_{key[3]}'
  def type_fn(key: LineComp) -> str:
    return ut.LINE_COMPRESSED

  return ut.reduce_graph_by_compression(
    g, line_comps, vertex_to_line_comp,
    key_fn, type_fn, reduce_io, file_name, props
  )

def merge_by_chunk(
  g: gt.Graph, reduce_io: bool, file_name: str, props: ut.CustomPropertiesList
) -> gt.GraphView:
  """Given a graph generated by yprov4Dask, i.e. a graph in which activities can
  be organized in chunks [see Dask documentation for information about chunks],
  groups chunks in single nodes. Returns the reduced graph."""

  def get_chunk_from_activity(key: str) -> str:
    last_stop = None

    for index in range(-1, -len(key), -1):
      curr = key[index]
      if curr == '_':
        last_stop = index
      elif not (curr >= '0' and curr <= '9'):
        break
  
    return key[:last_stop]
  
  def get_chunk_from_entity(key: str) -> str:
    activity_key_end = None
    for index in range(-1, -len(key), -1):
      if key[index] == '.':
        activity_key_end = index
        break
    if activity_key_end is not None:
      chunk = get_chunk_from_activity(key[:activity_key_end])
      return f'{chunk}{key[activity_key_end:]}'
    else:
      return key
    
  chunks: dict[str, set[int]] = {}
  vertex_to_chunk: dict[int, str] = {}
  ids = g.vertex_properties[ut.Props.ID.value]
  types = g.vertex_properties[ut.Props.TYPE.value]
  for v in g.vertices():
    chunk: str
    if types[v] == ut.ACTIVITY:
      chunk = get_chunk_from_activity(ids[v])
    elif types[v] == ut.ENTITY:
      chunk = get_chunk_from_entity(ids[v])
    else:
      chunk = ids[v]
    others: set[int] = chunks.get(chunk, set())
    others.add(v)
    chunks[chunk] = others
    vertex_to_chunk[v] = chunk

  def key_fn(key: str, level: int) -> str:
    return key

  return ut.reduce_graph_by_compression(
    g, chunks, vertex_to_chunk, key_fn, ut.type_unchunked_fn,
    reduce_io, file_name, props
  )