import argparse
import graph_tool.all as gt
import shutil
import os

import pattern_reducers as red
import utils as ut
import cluster_reducer as cl
import line_tracking as lt

parser = argparse.ArgumentParser(
  prog='reducer',
  description="""Given a provenance graph reduces it by means of node merging."""
)
parser.add_argument(
  'input_file', help='Path to the json file encoding the provenance graph'
)
parser.add_argument(
  '-o', '--output', default='./output',
  help="""Path to the folder into which all output files are put.
  By default all files are placed into ./output"""
)
parser.add_argument(
  '-e', '--entity_based', action='store_true',
  help="""Must be enabled when the input graph is entity-based, i.e. it relies
  on wasDerivedFrom relations between entities"""
)
parser.add_argument(
  '-p', '--props', default=None,
  help="""Path to a file in which each line contains a pair of strings defining,
  respectively, the key of a propery in entities, activities or agents (depending
  on what kind of vertex is reduced) and the type of value being stored in that
  property. A third integer value tells how each property should be treated when
  nodes are aggregated. If 0, the property is non recorded in the new node; if 1,
  a new property named <og_prop_name>_aggr is created with value, a list of all
  unique values of aggregated nodes.
  
  See graph_tools.VertexPropertyMap for a full list of accepted types."""
)
parser.add_argument(
  '-l', '--line_tracking', action='store_true',
  help="""When working with a document that embeds line tracking information,
  this option must be enabled to do a prereduction of the graph based on that
  information. The attributes that must be available in the document are:
  yprov4wfs:jupyter_cell_index, yprov4wfs:jupyter_cell_line,
  yprov4wfs:jupyter_cell_line_start, yprov4wfs:jupyter_cell_line_end. These
  attributes must be in the props file.
  """
)
parser.add_argument(
  '-c', '--chunked', action='store_true',
  help="""When working with a document that was generated by yProv4Dask and thus
  with a document in which node names carry a chunk index, merges together nodes
  whose name is the same except for the chunk index. This option has no effect
  if line_tracking is enabled.
  """
)
parser.add_argument(
  '-i', '--reduce_io', action='store_true',
  help="""If enabled looks for entities that serve as inputs to a single activity
  and aggregates them into a single entitiy. The same is done for output entities."""
)

args = parser.parse_args()

input_file = args.input_file
source_base_name, source_ext = os.path.splitext(os.path.basename(input_file))
output_dir = args.output
is_entity_based = args.entity_based
props = args.props
line_tracking = args.line_tracking
chunked = args.chunked
reduce_io = not is_entity_based and args.reduce_io

reduction_level = 0
def forge_name(level: int | str) -> str:
  file_name = f'{source_base_name}_{level}{source_ext}'
  return os.path.join(output_dir, file_name)

# Create the output dir an copy the input file in there
os.makedirs(output_dir, exist_ok=True)
source = forge_name(reduction_level)
shutil.copy(input_file, source)

graph: gt.Graph
with open(input_file, mode='r', encoding='utf-8') as file:
  graph, prefix, props = ut.from_prov_json(file, props)
  if ut.YPROVTOOLS not in prefix:
    prefix[ut.YPROVTOOLS] = ut.YPROVTOOLS_URL

def forge_motif_name(level: int | str) -> str:
  file_name = f'{source_base_name}_{level}.pdf'
  return os.path.join('motifs', file_name)

#subgraph: gt.GraphView
#if is_entity_based:
#  subgraph = red.get_entity_subgraph(graph)
#else:
#  subgraph = red.get_activity_subgraph(graph)
#i = 0
#k = 3
#motifs, counts, maps = cl.get_motifs(subgraph, k)
#while (len(motifs) > 0):
#  g = cl.reduce_by_motifs(
#    graph, k, motifs, counts, maps, forge_motif_name(i), props
#  )
#  graph = gt.Graph(g, prune=True)
#  ut.to_prov_json(graph, forge_name(i), prefix, props)
#  if is_entity_based:
#    subgraph = red.get_entity_subgraph(graph)
#  else:
#    subgraph = red.get_activity_subgraph(graph)
#  i += 1
#  motifs, counts, maps = cl.get_motifs(subgraph, k)
#  print(f'Iteration {i}')
#
#import sys
#sys.exit(0)

subgraph: gt.GraphView
if line_tracking:
  reduction_level += 1
  lt_graph = forge_name(reduction_level)
  subgraph = lt.merge_by_line(graph, is_entity_based, reduce_io, source, props)
  graph = gt.Graph(subgraph, prune=True)
  ut.to_prov_json(graph, lt_graph, prefix, props)
  source = lt_graph
elif chunked:
  reduction_level += 1
  uc_graph = forge_name(reduction_level)
  subgraph = lt.merge_by_chunk(graph, False, source, props)
  graph = gt.Graph(subgraph, prune=True)
  ut.to_prov_json(graph, uc_graph, prefix, props)
  source = uc_graph

  if reduce_io:
    reduction_level += 1
    uc_graph_io = forge_name(reduction_level)
    graph = ut.compress_io(graph, uc_graph, props, True, True, True)
    ut.to_prov_json(graph, uc_graph_io, prefix, props)
    source = uc_graph_io

if is_entity_based:
  subgraph = red.get_entity_subgraph(graph)
else:
  subgraph = red.get_activity_subgraph(graph)

patterns, vertex_to_patterns = red.find_patterns(subgraph)

while(len(patterns) > 0):
  print('ALL PATTERNS')
  for key in patterns:
    print(f'Pattern {key}:')
    for v in patterns[key]:
      print(f'\t{graph.vertex_properties['id'][v]}')

  reductibles, vertex_to_patterns = red.choose_patterns(patterns, vertex_to_patterns)
  print('REDUCING PATTERNS')
  for key in reductibles:
    print(f'Pattern {key}')

  filtered_patterns = { key: patterns[key] for key in reductibles }

  old_vertex_count = graph.num_vertices()
  old_edges_count = graph.num_edges()
  old_counts = ut.count_nodes_per_type(graph)

  reduced_graph = red.reduce(
    graph, filtered_patterns,
    vertex_to_patterns, reduce_io, source, props
  )
  reduction_level += 1
  source = forge_name(reduction_level)

  graph = gt.Graph(reduced_graph, prune=True)
  ut.to_prov_json(graph, source, prefix, props)
  
  print(f'Reduction {reduction_level}:')
  print(f'\tReduced {len(filtered_patterns)}/{len(patterns)}')
  new_counts = ut.count_nodes_per_type(reduced_graph)
  print(f'\tNodes: {old_vertex_count} -> {graph.num_vertices()}')
  print(f'\t\tActivities: {old_counts[ut.ACTIVITY]} -> {new_counts[ut.ACTIVITY]}')
  print(f'\t\tEntities: {old_counts[ut.ENTITY]} -> {new_counts[ut.ENTITY]}')
  print(f'\tEdges: {old_edges_count} -> {graph.num_edges()}')
  print('---------------------------------------------------------------------')

  if is_entity_based:
    subgraph = red.get_entity_subgraph(graph)
  else:
    subgraph = red.get_activity_subgraph(graph)
  patterns, vertex_to_patterns = red.find_patterns(subgraph)